image: java:8-jdk
image: docker:latest

stages:
  - assemble
  - test
  - build

assemble:
  stage: assemble
  script:
    - ./gradlew build
    - docker login registry.gitlab.com
    - docker build -t registry.gitlab.com/arichardson2189/authorization-svcsear .
  tags:
    - docker

test:
  stage: test
  script:
    - ./gradlew test

build:
  stage: build
  script:
    - docker push  registry.gitlab.com/arichardson2189/authorization-svcsear